site_name: iaqualink-py
site_description: Asynchronous Python library for Jandy iAqualink pool control systems
site_author: Florent Thoumie
site_url: https://flz.github.io/iaqualink-py/
repo_name: flz/iaqualink-py
repo_url: https://github.com/flz/iaqualink-py
edit_uri: edit/master/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - Authentication: getting-started/authentication.md
  - User Guide:
      - Systems: guide/systems.md
      - Devices: guide/devices.md
      - Examples: guide/examples.md
  - API Reference:
      - Client: api/client.md
      - System: api/system.md
      - Device: api/device.md
      - iAqua Systems: api/iaqua.md
      - eXO Systems: api/exo.md
      - Exceptions: api/exceptions.md
  - Development:
      - Contributing: development/contributing.md
      - Architecture: development/architecture.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            group_by_category: true
            show_category_heading: true
            show_if_no_docstring: false
            inherited_members: false
            filters:
              - "!^_"  # Exclude private members
            signature_crossrefs: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flz/iaqualink-py
