# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
VERSION_TUPLE = tuple[int | str, ...] if TYPE_CHECKING else object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = "0.5.1a1.dev11+g95ec4b9.d20240705"
__version_tuple__ = version_tuple = (0, 5, 1, "dev11", "g95ec4b9.d20240705")
